---

- name: Harden SSH configuration
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config.d/ssh-audit_hardening.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    create: true
    mode: '0640'
  loop:
    - regexp: '^(#)?Ciphers'
      line: "Ciphers {{ ciphers }}"
    - regexp: '^(#)?HostKeyAlgorithms'
      line: "HostKeyAlgorithms {{ host_key_algorithms }}"
    - regexp: '^(#)?KexAlgorithms'
      line: "KexAlgorithms {{ kex_algorithms }}"
    - regexp: '^(#)?MACs'
      line: "MACs {{ macs }}"
  notify: Restart sshd
...
