---

- name: Harden crypto in sshd_config
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    create: true
    mode: '0600'
  loop:
    - regexp: '^Ciphers'
      line: "Ciphers {{ ciphers }}"
    - regexp: '^HostKeyAlgorithms'
      line: "HostKeyAlgorithms {{ host_key_algorithms }}"
    - regexp: '^KexAlgorithms'
      line: "KexAlgorithms {{ kex_algorithms }}"
    - regexp: '^MACs'
      line: "MACs {{ macs }}"
  notify: Restart sshd
...
