---
# yamllint disable rule:line-length
# STRICT sshd crypto
# update-crypto-policies on RHEL 8.5 leaves weak algorithms due
# to the implementation in the python script.
- name: Override CRYPTO_POLICY for sshd
  lineinfile:
    path: /etc/sysconfig/sshd
    regex: '^CRYPTO_POLICY'
    line: "CRYPTO_POLICY='-oCiphers={{ Ciphers }} -oMACs={{ MACs }} -oKexAlgorithms={{ KexAlgorithms }} -oHostKeyAlgorithms={{ HostKeyAlgorithms }}'"
    state: present
    create: true
    mode: 0640
  notify: Restart sshd

- name: Configure strong entropy for sshd
  lineinfile:
    path: /etc/sysconfig/sshd
    regexp: '^SSH_USE_STRONG_RNG'
    line: 'SSH_USE_STRONG_RNG=32'
    state: present
    mode: 0640
  notify: Start RNG Entropy Gatherer
...
