---
# yamllint disable rule:line-length
# STRICT sshd crypto
# update-crypto-policies on RHEL 8.5 leaves weak algorithms due
# to the implementation in the python script.
- name: Override CRYPTO_POLICY for sshd
  ansible.builtin.lineinfile:
    path: /etc/sysconfig/sshd
    regex: '^CRYPTO_POLICY'
    line: "CRYPTO_POLICY='-oCiphers={{ ciphers }} -oMACs={{ macs }} -oKexAlgorithms={{ kex_algorithms }} -oHostKeyAlgorithms={{ host_key_algorithms }}'"
    state: present
    create: true
    mode: '0640'
  notify: Restart sshd

- name: Install rgn-tools for entropy, if available
  ansible.builtin.package:
    name:
      - rng-tools
    state: present
  ignore_errors: true  # when a repo doesn't list it
  register: entropy

- name: Configure strong entropy for sshd
  ansible.builtin.lineinfile:
    path: /etc/sysconfig/sshd
    regexp: '^SSH_USE_STRONG_RNG'
    line: 'SSH_USE_STRONG_RNG=32'
    state: present
    mode: '0640'
  when: entropy.changed | bool  # noqa no-handler
  notify: Start RNG Entropy Gatherer
...
