---

- name: Remove weak keys from sshd_config
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: 'HostKey /etc/ssh/{{ item }}'
    line: 'HostKey /etc/ssh/{{ item }}'
    state: absent
  notify: Restart sshd

- name: "Check weak key presence for {{ item }}"
  ansible.builtin.stat:
    path: "/etc/ssh/{{ item }}"
  register:
    weak_key_found

# Weak keys have weak permissions so sshd ignores them.
- name: "Disable weak host key {{ item }}"
  when:
    - weak_key_found.stat.exists is defined
    - weak_key_found.stat.exists|bool
  ansible.builtin.file:
    path: "/etc/ssh/{{ item }}"
    mode: 0666
...
