---

- name: "Mask generation of {{ item }} host key"
  ansible.builtin.systemd:
    name: "{{ hostkey }}"
    masked: true
  loop:
    - sshd-keygen@ecdsa.service
    - sshd-keygen@rsa.service
  loop_control:
    loop_var: hostkey

- name: Remove {{ item }} host key from sshd_config
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "HostKey /etc/ssh/ssh_host_{{ item }}_key"
    line: "HostKey /etc/ssh/ssh_host_{{ item }}_key"
    state: absent
  notify: Restart sshd

- name: "Remove {{ item }} host key"
  ansible.builtin.file:
    path: "/etc/ssh/ssh_host_{{ item }}_key"
    state: absent

...
