---
# Standards: 0.2
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: ssh-ubi8
    image: registry.access.redhat.com/ubi8/ubi-init
    pre_build_image: true
    command: /usr/sbin/init
    cgroupns_mode: host
    capabilities:
      - SYS_ADMIN
    published_ports:
      - 127.0.0.1:2211:22
    tmpfs:
      - /run
      - /tmp
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: yaml
      executable: /bin/bash
  playbooks:
    converge: ../resources/playbooks/converge.yml
    verify: ../resources/playbooks/verify.yml
verifier:
  name: ansible
...
