---
# Standards: 0.2
- name: Converge
  hosts: all

  vars:
    this_role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"

  tasks:
    - name: "Include {{ this_role }}"
      ansible.builtin.include_role:
        name: "{{ this_role }}"
...
